# Data Cleaning

## Objective
The goal of this notebook is to clean the raw dataset by:
- Checking data structure and quality
- Handling missing values
- Removing duplicates
- Standardizing column names
- Exporting a cleaned dataset for analysis and visualization

In [1]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv("../data/raw/wallacecommunications.csv")
df.head()

,ID,town,country,age,job,married,education,arrears,current_balance,housing,has_tv_package,last_contact,conn_tr,last_contact_this_campaign_day,last_contact_this_campaign_month,this_campaign,days_since_last_contact_previous_campaign,contacted_during_previous_campaign,outcome_previous_campaign,new_contract_this_campaign
0,32390233,Bristol,UK,39,management,married,tertiary,no,-1.90,no,yes,unknown,4,11,jun,8,-1,0,unknown,yes
1,41226029,Basildon,UK,53,housemaid,married,primary,no,3.62,no,no,cellular,1,28,jul,2,-1,0,unknown,yes
2,85498057,Blackburn,UK,79,retired,divorced,primary,no,27.87,no,no,telephone,3,13,jul,1,377,1,success,yes
3,76539627,Oldham,UK,43,services,single,secondary,no,5.50,yes,no,cellular,3,13,may,2,-1,0,unknown,no
4,76290986,Middlesbrough,UK,35,technician,single,secondary,no,3.44,no,no,cellular,2,27,aug,16,-1,0,unknown,yes

In [13]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50662 entries, 0 to 50661
Data columns (total 20 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         50662 non-null  int64
 1   town                                       50662 non-null  object
 2   country                                    50662 non-null  object
 3   age                                        50662 non-null  int64
 4   job                                        50662 non-null  object
 5   married                                    50662 non-null  object
 6   education                                  50662 non-null  object
 7   arrears                                    50662 non-null  object
 8   current_balance                            50662 non-null  float64
 9   housing                                    50662 non-null  object
 10  has_tv_package                             50662 non-null  object
 11  last_contact                               50662 non-null  object
 12  conn_tr                                    50662 non-null  int64
 13  last_contact_this_campaign_day             50662 non-null  int64
 14  last_contact_this_campaign_month           50662 non-null  object
 15  this_campaign                              50662 non-null  int64
 16  days_since_last_contact_previous_campaign  50662 non-null  int64
 17  contacted_during_previous_campaign         50662 non-null  int64
 18  outcome_previous_campaign                  50662 non-null  object
 19  new_contract_this_campaign                 50662 non-null  object
dtypes: float64(1), int64(7), object(12)
memory usage: 7.7+ MB

,ID,age,current_balance,conn_tr,last_contact_this_campaign_day,this_campaign,days_since_last_contact_previous_campaign,contacted_during_previous_campaign
count,5.066200e+04,50662.000000,50662.000000,50662.000000,50662.000000,50662.000000,50662.000000,50662.000000
mean,5.502871e+07,40.979373,13.991210,3.005093,15.768525,2.713217,42.644408,0.640283
std,2.598596e+07,10.919324,30.899163,1.409003,8.347083,3.052227,102.238078,2.358029
min,1.000073e+07,18.000000,-80.190000,1.000000,1.000000,1.000000,-1.000000,0.000000
25%,3.249964e+07,32.000000,0.820000,2.000000,8.000000,1.000000,-1.000000,0.000000
50%,5.501127e+07,39.000000,4.720000,3.000000,16.000000,2.000000,-1.000000,0.000000
75%,7.748809e+07,48.000000,14.950000,4.000000,21.000000,3.000000,-1.000000,0.000000
max,9.999952e+07,95.000000,984.170000,5.000000,31.000000,63.000000,871.000000,275.000000

In [14]:
df.isna().sum()

ID                                           0
town                                         0
country                                      0
age                                          0
job                                          0
married                                      0
education                                    0
arrears                                      0
current_balance                              0
housing                                      0
has_tv_package                               0
last_contact                                 0
conn_tr                                      0
last_contact_this_campaign_day               0
last_contact_this_campaign_month             0
this_campaign                                0
days_since_last_contact_previous_campaign    0
contacted_during_previous_campaign           0
outcome_previous_campaign                    0
new_contract_this_campaign                   0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [17]:
df.to_csv("../output/cleaned_data.csv", index=False)